sudo: required
services:
  - docker

before_install:
  - docker build -t rlustemberg/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true rlustemberg/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "dockr-react"
  env: "DockrReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-651245374920"
  bucket_path: "dockr-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
